# Generated by Django 6.0.1 on 2026-01-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saleshistory',
            unique_together={('product', 'timestamp')},
        ),
    ]
